#!/bin/sh
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
reset="$root/User/main.c"
config="$root/User/Config.h"
regs="$root/Driver/inc/stc8g1k08_regs.h"
project="$root/RVMDK/STC8G1K08-RESET.uvproj"
logic="$root/Driver/src/reset_controller.c"
uart="$root/Driver/src/uart.c"
maintenance_runtime="$root/Driver/src/maintenance_runtime.c"
maintenance_runtime_header="$root/Driver/inc/maintenance_runtime.h"
heartbeat="$root/Driver/src/heartbeat_monitor.c"
heartbeat_header="$root/Driver/inc/heartbeat_monitor.h"
reset_header="$root/Driver/inc/reset_controller.h"

fail() {
    printf '%s\n' "RESET 固件静态检查失败: $1" >&2
    exit 1
}

[ -f "$reset" ] || fail "缺少 User/main.c"
[ -f "$config" ] || fail "缺少 User/Config.h"
[ -f "$regs" ] || fail "缺少 Driver/inc/stc8g1k08_regs.h"
[ -f "$logic" ] || fail "缺少 reset_controller.c"
[ -f "$heartbeat_header" ] || fail "缺少 heartbeat_monitor.h"
[ -f "$heartbeat" ] || fail "缺少 heartbeat_monitor.c"
[ -f "$reset_header" ] || fail "缺少 reset_controller.h"
[ -f "$maintenance_runtime_header" ] || fail "缺少 maintenance_runtime.h"
[ -f "$maintenance_runtime" ] || fail "缺少 maintenance_runtime.c"
[ -f "$uart" ] || fail "缺少 uart.c"
[ -f "$project" ] || fail "缺少独立 RESET Keil 工程"

grep -Fq '<Device>STC8G1K08 Series</Device>' "$project" || fail "器件不是 STC8G1K08 Series"
grep -Fq '<FilePath>..\Driver\src\maintenance_runtime.c</FilePath>' "$project" || fail "工程未引用 maintenance_runtime"
grep -Fq '<FilePath>..\Driver\src\uart.c</FilePath>' "$project" || fail "工程未引用 UART 模块"
grep -Fq '<OutputName>stc8g1k08_reset</OutputName>' "$project" || fail "输出名不正确"
grep -Fq '<FilePath>..\User\main.c</FilePath>' "$project" || fail "工程未引用 main.c"
grep -Fq '<FilePath>..\Driver\src\heartbeat_monitor.c</FilePath>' "$project" || fail "工程未引用心跳状态模块"
grep -Fq '<FilePath>..\Driver\src\reset_controller.c</FilePath>' "$project" || fail "工程未引用复位状态模块"

grep -Fq '#define AP_RESET_ASSERT_LEVEL 0U' "$config" || fail "缺少复位极性配置"
grep -Fq '#define STC8G1K08_FIRMWARE_VERSION "1.0.6"' "$config" || fail "版本应为 1.0.6（含 trailer 事件锁存）"
grep -Fq 'STC8G1K08 reset firmware v' "$reset" || fail "启动横幅未包含固件版本"
grep -Eq '#define STC8G1K08_UART_LOG_ENABLE [01]U' "$config" || fail "UART 日志开关缺失"
grep -Fq '#define HEARTBEAT_MONITOR_TIMEOUT_MS 5000UL' "$config" || fail "心跳超时不是 5 秒"
grep -Fq 'SCON = 0x40' "$uart" || fail "UART 未设置为 TX-only"
grep -Fq 'void uart1_putc(char value)' "$uart" || fail "缺少 UART TX 接口"
! grep -Fq 'void uart1_isr(void) interrupt 4' "$uart" || fail "UART RX ISR 仍存在"
! grep -Fq 'ES = 1' "$uart" || fail "UART 中断仍启用"
! grep -Fq 'g_uart_rx_buffer' "$uart" || fail "UART RX 缓冲仍存在"
! grep -Fq 'uart1_read_byte' "$uart" || fail "UART RX API 仍存在"
! grep -Fq 'uart1_rx_overflow_take' "$uart" || fail "UART RX 溢出 API 仍存在"
[ ! -e "$root/RVMDK/STC8G1K08-SMOKE.uvproj" ] || fail "正式工程目录仍包含 SMOKE 工程"
[ ! -e "$root/RVMDK/STC8G1K08-MONITOR.uvproj" ] || fail "正式工程目录仍包含 MONITOR 工程"
grep -Fq '#define AP_RESET_PULSE_MS 200UL' "$config" || fail "缺少复位脉宽配置"
grep -Fq '#define RESET_HEARTBEAT_GRACE_MS 30000UL' "$config" || fail "RESET 启动宽限不足"
grep -Fq '#define WDT_PRESCALE 6U' "$config" || fail "WDT 分频不是 128"
grep -Fq 'sfr WDT_CONTR = 0xC1' "$regs" || fail "缺少 WDT_CONTR SFR"
grep -Fq 'P5M1 |= P5_AP_RESET_MASK' "$reset" || fail "P5.5 没有高阻释放路径"
grep -Fq 'P5M0 |= P5_AP_RESET_MASK' "$reset" || fail "P5.5 没有复位推挽路径"
grep -Fq 'WDT_CONTR = (unsigned char)(WDT_PRESCALE | WDT_ENABLE_MASK)' "$reset" || fail "没有启动内部 WDT"
grep -Fq '#include "uart.h"' "$reset" || fail "main.c 未接入 UART 模块"
grep -Fq '#include "maintenance_runtime.h"' "$reset" || fail "main.c 未接入 maintenance_runtime"
grep -Fq 'maintenance_runtime_init' "$reset" || fail "未初始化 maintenance_runtime"
grep -Fq 'maintenance_runtime_on_falling_edge' "$reset" || fail "INT2 未调用 maintenance_runtime 解码器"
grep -Fq 'maintenance_runtime_poll' "$reset" || fail "主循环未轮询维护事件"
grep -Fq 'static maintenance_runtime_t g_maintenance_runtime;' "$reset" || fail "维护运行时不应放入 XDATA"
! grep -Fq 'maintenance_runtime_t xdata g_maintenance_runtime' "$reset" || fail "维护运行时不应放入 XDATA"
grep -Fq 'MRT_EVENT_ENTER' "$reset" || fail "未处理 ENTER 事件"
grep -Fq 'MRT_EVENT_EXIT' "$reset" || fail "未处理 EXIT 事件"
grep -Fq 'MRT_EVENT_EXPIRED' "$reset" || fail "未处理 EXPIRED 事件"
grep -Fq 'MRT_MODE_MAINTENANCE' "$reset" || fail "未检查维护模式"
! grep -Fq 'g_command_length' "$reset" || fail "UART 命令缓冲残留"
! grep -Fq 'app_poll_commands' "$reset" || fail "UART 命令轮询残留"
grep -Fq 'static void app_report' "$reset" || fail "缺少周期状态输出"
grep -Fq 'heartbeat_snapshot(' "$reset" || fail "缺少单次心跳快照"
grep -Fq '#if STC8G1K08_UART_LOG_ENABLE' "$uart" || fail "UART 实现未受编译开关控制"
grep -Fq '#ifdef HEARTBEAT_MONITOR_HOST_TEST' "$heartbeat" || fail "心跳测试查询未隔离"
grep -Fq '#ifdef RESET_CONTROLLER_HOST_TEST' "$logic" || fail "复位状态查询未隔离"
grep -Fq '#ifdef HEARTBEAT_MONITOR_HOST_TEST' "$heartbeat_header" || fail "心跳测试 API 声明未隔离"
grep -Fq '#ifdef RESET_CONTROLLER_HOST_TEST' "$reset_header" || fail "复位测试 API 声明未隔离"
grep -Fq 'static volatile heartbeat_monitor_ms_t g_millisecond;' "$reset" || fail "毫秒时基应放入 DATA"
! grep -Fq 'static volatile heartbeat_monitor_ms_t xdata g_millisecond;' "$reset" || fail "毫秒时基不应放入 XDATA"
! grep -Fq 'g_last_cpu_check_edge_ms' "$reset" || fail "直接心跳路径不应维护额外边沿时间戳"
grep -Fq 'heartbeat_monitor_t heartbeat;' "$reset" || fail "主循环缺少局部心跳快照"
! grep -Fq 'g_decision_snapshot' "$reset" || fail "不应保留决策快照日志"
! grep -Fq 'heartbeat_status_snapshot' "$reset" || fail "不应保留分离的心跳状态快照"
! grep -Fq 'g_millis_snapshot_value' "$reset" || fail "不应保留 XDATA 毫秒暂存"
! grep -Fq 'g_heartbeat_status_value' "$reset" || fail "不应保留 XDATA 心跳状态暂存"
! grep -Fq 'g_saved_ea' "$reset" || fail "不应保留共享 EA 暂存"
! grep -Fq 'g_app_now_ms' "$reset" || fail "不应保留 XDATA 主循环时间暂存"
! grep -Fq 'g_report_last_edge_ms' "$reset" || fail "不应保留 XDATA 报告边沿暂存"
! grep -Fq 'g_report_edge_count' "$reset" || fail "不应保留 XDATA 报告计数暂存"
! grep -Fq 'g_report_edge_seen' "$reset" || fail "不应保留报告边沿标志暂存"
! grep -Fq 'g_app_heartbeat_status' "$reset" || fail "不应保留 XDATA 主循环状态暂存"
! grep -Fq 'g_last_report_ms' "$reset" || fail "不应保留 XDATA 周期报告时间暂存"
! grep -Fq 'CPU_CHECK_HEARTBEAT_MIN_INTERVAL_MS' "$config" || fail "基线固件不应配置边沿过滤"
! grep -Fq 'CPU_CHECK_HEARTBEAT_MAX_INTERVAL_MS' "$config" || fail "基线固件不应配置边沿过滤"
grep -Fq 'heartbeat_monitor_on_falling_edge(&g_heartbeat_monitor, now_ms);' "$reset" || fail "INT2 未先记录心跳"
grep -Fq 'maintenance_runtime_on_falling_edge(&g_maintenance_runtime, now_ms);' "$reset" || fail "INT2 未在心跳后调用解码器"
grep -Fq 'maintenance_runtime_snapshot(&mrt_event, &mrt_mode, now_ms);' "$reset" || fail "维护状态轮询未使用临界区快照"
grep -Fq 'heartbeat_monitor_init(&g_heartbeat_monitor, now_ms);' "$reset" || fail "恢复正常模式未重置心跳宽限"
grep -Fq 'if (mrt_event == MRT_EVENT_EXIT || mrt_event == MRT_EVENT_EXPIRED)' "$reset" || fail "恢复事件未跳过旧心跳快照"
grep -Fq '#if STC8G1K08_UART_LOG_ENABLE' "$reset" || fail "UART 输出未受编译开关控制"
grep -Fq 'WDT_CONTR |= WDT_CLEAR_MASK' "$reset" || fail "没有清除内部 WDT"
grep -Fq 'g_reset_output_active = 0U' "$reset" || fail "上电默认输出不是安全状态"
grep -Fq 'reset_controller_output_active' "$reset" || fail "未应用复位状态机输出"
grep -Fq 'void int2_isr(void) interrupt 10' "$reset" || fail "未注册 INT2"

! grep -Fq 'app_take_decision_snapshot' "$reset" || fail "不应保留决策快照采集"
! grep -Fq 'app_report_output_transition' "$reset" || fail "不应保留输出转换诊断"
! grep -Fq 'reason=timeout' "$reset" || fail "不应保留决策快照断言日志"
! grep -Fq 'p54_at_decision=' "$reset" || fail "不应保留决策快照字段"

printf '%s\n' 'OK: STC8G1K08 RESET 固件静态检查通过'
